spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    username: "root"
    password: "000000"
    url: jdbc:mysql://localhost:3306/rmg_database?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  #thymeleaf
  thymeleaf:
    suffix: .html
    enabled: true
    cache: false
    prefix: classpath:/template/
    check-template-location: true
    mode: HTML
  data:
    redis:
      port: 6379
      host: 127.0.0.1

#mapper 位置
mybatis:
  mapper-locations: classpath:/mapper/*.xml

#服务器
server:
  address: 0.0.0.0
  tomcat:
    max-swallow-size: 100MB

#IP配置
IPConfig:
  #  frontIP: https://stcq1wl2-5.asse.devtunnels.ms/
  frontIP: 127.0.0.1:5173
  static-resource-ip: localhost:81

#头像上传
uploadPath: "G:\\github-progect\\rmg-system\\rmg-system-java\\src\\main\\resources\\static\\users_profile\\"

#debug mode
logging:
  level:
    com:
      rockeven199:
        rmg:
          mapper: debug